import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import { Crimson_Text } from "next/font/google";
import { Pacifico } from "next/font/google";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });
//
// const crimsonText = Crimson_Text({
//   subsets: ["latin"],
//   weight: ["600", "400"],
//   display: "swap",
//   variable: "--font-crimson",
// });
export const pacifico = Pacifico({
  weight: "400", // Pacifico only has 400
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${pacifico.className} antialiased`}>{children}</body>
    </html>
  );
}
